name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle files
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Decrypt google-services files
        run: |
          gpg -d --batch --passphrase ${{ GOOGLE_SERVICES_PASS }} app/src/free/google-services.json.gpg > app/src/free/google-services.json
          gpg -d --batch --passphrase ${{ GOOGLE_SERVICES_PASS }} app/src/paid/google-services.json.gpg > app/src/paid/google-services.json

      - name: Build with Gradle
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}
        run: ./gradlew assembleDebug

      - name: Unit Tests
        env:
          ZTM_API_KEY: ${{ secrets.ZTM_API_KEY }}
        run: ./gradlew test